version: "3.3"
services:
  nginx:
    depends_on:
      - console
      - api
    restart: always # because it is routing traffic to our entire app
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
    networks:
      - ecsd-app
  console:
    build:
      context: ./console
      dockerfile: Dockerfile_clean
    #ports:
    #  - '3000:3000'
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    restart: on-failure
    container_name: nginx
    networks:
      - ecsd-app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile_clean
    #ports:
    #  - '3001:3001'
    restart: on-failure
    container_name: api
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    env_file:
      - ./.env
    networks:
      - ecsd-app
networks:
  ecsd-app:
    external: true

  #mongo:
  #  image: 'mongo'
  #  container_name: 'mongo-db'
  #  ports:
  #    - '27017-27019:27017-27019'
  #  volumes: 
      #- ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  #    - ./db/mongo-volume:/data/db
    #env_file:
    #  - ./env/mongo.env