upstream api {
  server 172.17.0.1:8080;
}

upstream console {
  server 172.17.0.1:8081;
}  

upstream expert {
  server 172.17.0.1:8082;
}  

server {
  listen 80;
  #underscores_in_headers on;
  return 301 https://$host$request_uri;

  }

server {
    listen 443 ssl;
    listen [::]:443 ssl ;

    #server_name app.ecscompliance.com;
   
    #access_log /dev/stdout ;
    #error_log /dev/stderr debug ;


    #server_tokens off;

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    #ssl_buffer_size 8k;

    #ssl_dhparam /etc/ssl/certs/dhparam-2048.pem;

    #ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    #ssl_prefer_server_ciphers on;

    #ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5;

    #ssl_ecdh_curve secp384r1;
    #ssl_session_tickets off;

    # OCSP stapling
    #ssl_stapling on;
    #ssl_stapling_verify on;
    #resolver 8.8.8.8;


    # Define the specified charset to the “Content-Type” response header field
    #charset utf-8;


  location /api {
    rewrite /api/(.*) /$1 break;
    expires -1;
    add_header Cache-Control no-store;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass_request_headers      on;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Authorization $http_authorization;
    proxy_pass http://api;
  }

  location /expert {
    rewrite /expert/(.*) /$1 break;
    expires -1;
    add_header Cache-Control no-store;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass_request_headers      on;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Authorization $http_authorization;
    proxy_pass http://expert;
  }


  location / {
    #rewrite /console/(/.*|$) /$1 break; 
    expires -1;
    add_header Cache-Control no-store;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass_request_headers      on;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Authorization $http_authorization;
    proxy_pass http://console;
  }

}


