services:
  nginx: 
    image: ghcr.io/llamalogic/nginx
    #image: nginx:latest 
    hostname: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      #- ./nginx/conf/:/etc/nginx/conf.d/:rw
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/nginx/ssl/:rw
    networks:
      ecsd-app:
        aliases:
          - nginx
  api:
    image: ghcr.io/llamalogic/api
    env_file: ./.env-api
    hostname: api
    volumes:
      - ./files/:/usr/node/app/files/:rw 
    networks:
      ecsd-app:
        aliases:
          - api
  console:
    image: ghcr.io/llamalogic/console
    env_file: ./.env-console
    environment:
      ENV_FILE_IN: "/usr/share/nginx/html/runtime-env.env"
    hostname: console
    volumes:
      - ./.env-console:/usr/share/nginx/html/runtime-env.env
    networks:
      ecsd-app:
        aliases:
          - console      
  mail:
    image: ghcr.io/llamalogic/mail
    env_file: ./.env-mail
    hostname: mail
    networks:
      ecsd-app:
        aliases:
          - mail
  expert:
    image: ghcr.io/llamalogic/expert
    env_file: ./.env-expert
    hostname: expert
    networks:
      ecsd-app:
        aliases:
          - expert
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
networks:
  ecsd-app:
