name: authentication_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  scrollable_positioned_list: ^0.3.8
  url_launcher: ^6.2.6
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^10.0.0
  mask_text_input_formatter: ^2.1.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.0.0
  flutter_painter:
    git:
      url: https://github.com/LlamaLogic/flutter_painter.git
      ref: master
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.1.0
  
 
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.1
  formz: ^0.6.0
  intl: ^0.19.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.7.0

assets:
  - lib/assets/.env
  - lib/assets/.env.dev
